// -----------------------------------------------------------------------
// <auto-generated>
//    此代码由代码生成器生成。
//    手动更改此文件可能导致应用程序出现意外的行为。
//    如果重新生成代码，对此文件的任何修改都会丢失。
//    如果需要扩展此类，可以遵守如下规则进行扩展：
//      1.横向扩展：如需给当前控制器添加API，请在控制器类型 ReportOutController.cs 进行添加
//      2.纵向扩展：如需要重写当前控制器的API实现，请在控制器类型 ReportOutController.cs 进行继承重写
// </auto-generated>
//
//  <copyright file="ReportOutBase.generated.cs" company="teng.kun">
//      teng.kun
//  </copyright>
//  <site>http://teng.kun</site>
//  <last-editor>teng.kun</last-editor>
// -----------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

using OSharp.AspNetCore.Mvc;
using OSharp.AspNetCore.Mvc.Filters;
using OSharp.AspNetCore.UI;
using OSharp.Caching;
using OSharp.Authorization.Functions;
using OSharp.Authorization.Modules;
using OSharp.Data;
using OSharp.Entity;
using OSharp.Filter;
using OSharp.Security;

using teng.kun.ReportOutIn;
using teng.kun.ReportOutIn.Dtos;
using teng.kun.ReportOutIn.Entities;


namespace teng.kun.Web.Areas.Admin.Controllers
{
    /// <summary>
    /// 管理控制器基类: 出库报表信息
    /// </summary>
    [ModuleInfo(Position = "ReportOutIn", PositionName = "报表信息模块")]
    [Description("管理-出库报表信息")]
    public abstract class ReportOutControllerBase : AdminApiController
    {
        /// <summary>
        /// 初始化一个<see cref="ReportOutController"/>类型的新实例
        /// </summary>
        protected ReportOutControllerBase(IReportOutInContract reportOutInContract,
            IFilterService filterService)
        {
            ReportOutInContract = reportOutInContract;
            FilterService = filterService;
        }

        /// <summary>
        /// 获取或设置 数据过滤服务对象
        /// </summary>
        protected IFilterService FilterService { get; }

        /// <summary>
        /// 获取或设置 报表信息模块业务契约对象
        /// </summary>
        protected IReportOutInContract ReportOutInContract { get; }
        
        /// <summary>
        /// 读取出库报表列表信息
        /// </summary>
        /// <param name="request">页请求信息</param>
        /// <returns>出库报表列表分页信息</returns>
        [HttpPost]
        [ModuleInfo]
        [Description("读取")]
        public virtual PageData<ReportOutOutputDto> Read(PageRequest request)
        {
            Check.NotNull(request, nameof(request));

            Expression<Func<ReportOut, bool>> predicate = FilterService.GetExpression<ReportOut>(request.FilterGroup);
            var page = ReportOutInContract.ReportOuts.ToPage<ReportOut, ReportOutOutputDto>(predicate, request.PageCondition);

            return page.ToPageData();
        }
    }
}
